spring.application.name=careertrack
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/careertrack
spring.datasource.username=root
spring.datasource.password=adiSql@22

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=careertrack-secret-key-for-jwt-authentication-2026
jwt.expiration=3600000